//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatriaManagementSystem__Event_Project_
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffUser
    {
        public long ID { get; set; }
        public long StaffID { get; set; }
        public Nullable<long> BlockID { get; set; }
        public decimal Salary { get; set; }
        public Nullable<bool> SuperAdmin { get; set; }
        public System.DateTime DateStartWork { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual User User { get; set; }
    }
}
