//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatriaManagementSystem__Event_Project_
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentUser
    {
        public long ID { get; set; }
        public long StudentID { get; set; }
        public string MatircNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
